PROGRAM SIMPSONS
    INTEGER :: INTERVALS, K
    REAL :: LOWER_LIMIT, UPPER_LIMIT, X1, F1, SUM_ONE_THIRD, SUM_THREE_EIGHTH
    REAL :: S13, S38, EXACT, ERR13, ERR38, STEP

    F(X)=1.0/(1.0+X**2)
    LOWER_LIMIT=0.0
    UPPER_LIMIT=6.0
    INTERVALS=24
    STEP=(UPPER_LIMIT-LOWER_LIMIT)/FLOAT(INTERVALS)
    S13=(F(LOWER_LIMIT)+F(UPPER_LIMIT))
    S38=(F(LOWER_LIMIT)+F(UPPER_LIMIT))

    DO K=1,INTERVALS-1
        X1=LOWER_LIMIT+FLOAT(K)*STEP
        F1=F(X1)
        IF(MOD(K,2).EQ.0)THEN
            S13=S13+2.0*F1
        ELSE
            S13=S13+4.0*F1
        ENDIF
            IF(MOD(K,3).EQ.0)THEN
            S38=S38+2.0*F1
        ELSE
            S38=S38+3.0*F1
        ENDIF
    ENDDO

    SUM_ONE_THIRD=S13*(STEP/3.0)
    SUM_THREE_EIGHTH=S38*(3.0*STEP/8.0)
    EXACT=ATAN(UPPER_LIMIT)-ATAN(LOWER_LIMIT)
    ERR13=ABS(EXACT-SUM_ONE_THIRD)
    ERR38=ABS(EXACT-SUM_THREE_EIGHTH)

    PRINT*,"SIMPSON'S RULE INTEGRATION: 1/(1+X^2) FROM 0 TO 6"
    PRINT*,"=================================================="
    PRINT*,"EXACT VALUE      = ",EXACT
    PRINT*,"SIMPSON'S 1/3    = ",SUM_ONE_THIRD
    PRINT*,"ERROR IN 1/3     = ",ERR13
    PRINT*,"SIMPSON'S 3/8    = ",SUM_THREE_EIGHTH
    PRINT*,"ERROR IN 3/8     = ",ERR38
    PRINT*,""
    IF(ERR13.LT.ERR38)THEN
    PRINT*,"SIMPSON'S 1/3 rule is more accurate"
    ELSE
    PRINT*,"SIMPSON'S 3/8 rule is more accurate"
    ENDIF
END PROGRAM