PROGRAM NEWTONFORWARDINTERPOLATION
    IMPLICIT NONE

    INTEGER, PARAMETER :: N = 5
    REAL, PARAMETER :: X_INTERP = 2003.0

    INTEGER :: I, J
    REAL :: X(N), Y(N), COEFFICIENTS(N), F, TERM

    X = [2000.0, 2005.0, 2010.0, 2015.0, 2020.0]
    Y = [100.0,  125.0,  139.0,  200.0,  250.0]

    ! BUILD DIVIDED DIFFERENCE COEFFICIENTS
    COEFFICIENTS = Y
    DO I = 2, N
        DO J = N, I, -1
            COEFFICIENTS(J) = (COEFFICIENTS(J) - COEFFICIENTS(J-1)) / (X(J) - X(J-I+1))
        END DO
    END DO

    ! NEWTON'S INTERPOLATION FORMULA
    F = COEFFICIENTS(1)
    DO I = 2, N
        TERM = COEFFICIENTS(I)
        DO J = 1, I-1
            TERM = TERM * (X_INTERP - X(J))
        END DO
        F = F + TERM
    END DO

    WRITE(*, 100) F
100 FORMAT("F(2003) = ", F12.6)

END PROGRAM NEWTONFORWARDINTERPOLATION
