PROGRAM NEWTONBACKWARDINTERPOLATION
    IMPLICIT NONE

    INTEGER, PARAMETER :: N = 5
    REAL, PARAMETER :: X_INTERP = 2018.0

    REAL :: X(N), Y(N), COEFFICIENTS(N)
    REAL :: F, TERM
    INTEGER :: I, J

    X = [2000.0, 2005.0, 2010.0, 2015.0, 2020.0]
    Y = [100.0,  125.0,  139.0,  200.0,  250.0]

    ! BUILD BACKWARD DIVIDED DIFFERENCE COEFFICIENTS
    COEFFICIENTS = Y
    DO I = 2, N
        DO J = 1, N-I+1
            COEFFICIENTS(J) = (COEFFICIENTS(J+1) - COEFFICIENTS(J)) / (X(J+I-1) - X(J))
        END DO
    END DO

    ! NEWTON'S BACKWARD INTERPOLATION FORMULA
    F = COEFFICIENTS(N)
    DO I = 2, N
        TERM = COEFFICIENTS(N-I+1)
        DO J = 1, I-1
            TERM = TERM * (X_INTERP - X(N-J+1))
        END DO
        F = F + TERM
    END DO

    WRITE(*, 100) F
100 FORMAT("F(2018) = ", F12.6)

END PROGRAM NEWTONBACKWARDINTERPOLATION
