PROGRAM TRAPEZOIDAL
    IMPLICIT NONE

    INTEGER :: INTERVAL, K
    REAL :: LOWER_LIMIT, UPPER_LIMIT, X, FX, STEP
    REAL :: SUM, RESULT, EXACT, ERROR
    REAL :: F

    F(X) = SQRT(1.0 - X**2)

    LOWER_LIMIT = 0.0
    UPPER_LIMIT = 1.0
    INTERVAL    = 24

    STEP = (UPPER_LIMIT - LOWER_LIMIT) / REAL(INTERVAL)

    SUM = F(LOWER_LIMIT) + F(UPPER_LIMIT)

    DO K = 1, INTERVAL - 1
        X   = LOWER_LIMIT + REAL(K) * STEP
        FX  = F(X)
        SUM = SUM + 2.0 * FX
    END DO

    RESULT = SUM * (STEP / 2.0)
    EXACT  = ASIN(UPPER_LIMIT) - ASIN(LOWER_LIMIT)
    ERROR  = ABS(EXACT - RESULT)


    WRITE(*, 300) RESULT
300 FORMAT("  RESULT    = ", F10.6)
    WRITE(*, 400) EXACT
400 FORMAT("  EXACT     = ", F10.6)
    WRITE(*, 500) ERROR
500 FORMAT("  ERROR     = ", F10.6)

END PROGRAM TRAPEZOIDAL
